# -*- coding: utf-8 -*-
"""Dice Game Double play.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWzTLl1fIgt1ZmMYS9O9QbMhmD2EuLU1
"""

import random

print("Welcome to the Dice Game, if you win you win double!")

play = input("Would you like to play? (yes/no) ").lower()

if play != "yes":
    print("Goodbye!")
else:
    wager = int(input("How much would you like to wager? (enter an integer less than or equal 100) "))

    # Validate wager
    if wager <= 0:
        print("invalid wager")
    elif wager > 100:
        print("That's too much sorry")
    else:
        # ---------- PART 1 ----------
        guess = int(input("What is your guess number guess? (1-6) "))
        dice_roll = random.randint(1, 6)

        if guess == dice_roll:
            print(f"Congratulations, you win {wager * 2}")
            current_amount = wager * 2
        else:
            print(f"You lost your wager {wager}")
            current_amount = -wager

        # ---------- DOUBLE PLAY ----------
        double_play_amount = abs(current_amount) * 2

        choice = input(f"\nWould you like to go double play for {double_play_amount}? (yes/no) ").lower()

        if choice != "yes":
            print(f"Thank you, your current total is {current_amount}")
        else:
            second_guess = int(input("What is your guess number guess? (1-6) "))
            second_dice_roll = random.randint(1, 6)

            if second_guess == second_dice_roll:
                current_amount += double_play_amount
                print(f"Wow! you won all {current_amount} in total")
            else:
                current_amount -= double_play_amount
                print(f"You lose all {current_amount} in total")

