# -*- coding: utf-8 -*-
"""simple_dice_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sZp-t89Fr7nGJLVfAb2wIpkJAUxlZM5

**Part 1: Simple Dice Game**
"""

import random

print("Welcome to the Dice Game")

play = input("Would you like to play? (yes/no): ").lower()

if play != "yes":
    print("Maybe next time. Goodbye!")
else:
    wager = int(input("How much would you like to wager? (enter an integer ≤ 100): "))

    # Validate wager FIRST
    if wager <= 0:
        print("Invalid wager")
    elif wager > 100:
        print("That's too much sorry")
    else:
        guess = int(input("What is your guess number? (1-6): "))

        # Validate guess
        if guess < 1 or guess > 6:
            print("Invalid guess. Please choose a number between 1 and 6.")
        else:
            dice = random.randint(1, 6)
            print(f"The dice rolled: {dice}")

            if guess == dice:
                winnings = wager * 2
                print(f"Congratulations, you win {winnings}")
            else:
                print("Sorry, you lost")